---
players:
- !ruby/object:Player
  first_name: Al
  last_name: Delcy
  nickname: aldelcy
  email: aldelcy2000@gmail.com
  pin: '1234'
  profile_pic: aldelcy.jpg
  stat:
    :win: 0
    :losse: 0
    :tie: 0